--- #YAML:1.0
name:               Dancer-Plugin-REST
version:            0.05
abstract:           REST plugin for Dancer
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.87
requires:
    Dancer:  1.3014
    JSON:    0
resources:
    repository:  http://github.com/sukria/Dancer-Plugin-REST
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
