--- #YAML:1.0
name:               Dancer-Plugin-REST
version:            0.02
abstract:           REST plugin for Dancer
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:      1.178_01
    JSON:        0
    Test::More:  0.87
resources:
    repository:  http://github.com/sukria/Dancer-Plugin-REST
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
